<?php

use Drupal\quizz_migrate\Branch4x\QuestionDetailMigration;

/**
 * Implements hook_migrate_api().
 */
function quizz_migrate_migrate_api() {
  $api = array('api' => 2, 'migrations' => array());

  $api['groups']['quiz4x']['title'] = 'Quiz [4x]';
  $api['groups']['quiz4x_question']['title'] = 'Quiz question [4x]';
  $api['groups']['quiz4x_question_revision']['title'] = 'Quiz question revision [4x]';
  $api['groups']['quiz4x_question_details']['title'] = 'Quiz question details [4x]';

  $api['migrations'] += array(
      'quiz'          => array(
          'class_name' => 'Drupal\quizz_migrate\Branch4x\QuizMigration',
          'group_name' => 'quiz4x',
      ),
      'quiz_revision' => array(
          'class_name'   => 'Drupal\quizz_migrate\Branch4x\QuizRevisionMigration',
          'group_name'   => 'quiz4x',
          'dependencies' => array('quiz'),
      ),
  );

  $api['migrations'] += array(
      'quiz_question_type' => array(
          'class_name' => 'Drupal\quizz_migrate\Branch4x\QuestionTypeMigration',
          'group_name' => 'quiz4x',
      ),
  );

  $api['migrations'] += array(
      'quiz_relationship' => array(
          'class_name'   => 'Drupal\quizz_migrate\Branch4x\RelationshipMigration',
          'group_name'   => 'quiz4x',
          'dependencies' => array('quiz_revision', 'quiz_question_type'),
      ),
  );

  $api['migrations'] += array(
      'quiz_result' => array(
          'class_name'   => 'Drupal\quizz_migrate\Branch4x\ResultMigration',
          'group_name'   => 'quiz4x',
          'dependencies' => array('quiz_relationship'),
      ),
      'quiz_answer' => array(
          'class_name'   => 'Drupal\quizz_migrate\Branch4x\AnswerMigration',
          'group_name'   => 'quiz4x',
          'dependencies' => array('quiz_result'),
      ),
  );

  return $api;
}

/**
 * Implements hook_enable().
 */
function quizz_migrate_enable() {
  Migration::deregisterMigration('quiz_question');
}

function quizz_migrate_enable_question_type($node_type) {
  if (!quizz_question_get_handler_info($node_type)) {
    return;
  }

  $base = array('bundle' => $node_type);

  $qm_class = 'Drupal\quizz_migrate\Branch4x\QuestionMigration';
  $qm_name = "quiz_question__{$node_type}";
  Migration::registerMigration($qm_class, $qm_name, $base + array('group_name' => 'quiz4x_question'));

  $qrm_class = 'Drupal\quizz_migrate\Branch4x\QuestionRevisionMigration';
  $qrm_name = "quiz_question_revision__{$node_type}";
  Migration::registerMigration($qrm_class, $qrm_name, $base + array('group_name' => 'quiz4x_question_revision'));

  // Try, valid details handler found -- no exception.
  $migration = new QuestionDetailMigration($base);
  if ($migration->getDetailsHandler()) {
    $qhm_class = get_class($migration);
    $qhm_name = "quiz_question_details__{$node_type}";
    Migration::registerMigration($qhm_class, $qhm_name, $base + array('group_name' => 'quiz4x_question_details'));
  }
}

/**
 * Implements hook_modules_enabled()
 */
function quizz_migrate_modules_enabled($modules) {
  foreach ($modules as $module) {
    if (function_exists("{$module}_quizz_question_info")) {
      quizz_migrate_module_enabled($module);
    }
  }
}

function quizz_migrate_module_enabled($module) {
  $handlers = module_invoke($module, 'quizz_question_info');
  foreach (array_keys($handlers) as $name) {
    if (db_query('SELECT 1 FROM {node_type} WHERE type = :type', array(':type' => $name))->fetchColumn()) {
      quizz_migrate_enable_question_type($name);
    }
  }
}
