<?php

/**
 * Implements hook_migrate_api().
 */
function quizz_migrate_migrate_api() {
  $api = array('api' => 2, 'migrations' => array());

  $api['groups']['quiz4x']['title'] = 'Quiz 4x';
  $api['groups']['quiz4x_question']['title'] = 'Quiz question 4x';
  $api['groups']['quiz4x_question_revision']['title'] = 'Quiz question revision 4x';

  $api['migrations'] += array(
      'quiz'          => array(
          'class_name' => 'Drupal\quizz_migrate\Branch4x\QuizMigration',
          'group_name' => 'quiz4x',
      ),
      'quiz_revision' => array(
          'class_name'   => 'Drupal\quizz_migrate\Branch4x\QuizRevisionMigration',
          'group_name'   => 'quiz4x',
          'dependencies' => array('quiz'),
      ),
  );

  $api['migrations'] += array(
      'quiz_question_type' => array(
          'class_name' => 'Drupal\quizz_migrate\Branch4x\QuestionTypeMigration',
          'group_name' => 'quiz4x',
      ),
      'quiz_question'      => array(
          'class_name'   => 'Drupal\quizz_migrate\Branch4x\QuestionMigration',
          'group_name'   => 'quiz4x_question',
          'dependencies' => array('quiz_question_type'),
      ),
  );

  $api['migrations'] += array(
      'quiz_relationship' => array(
          'class_name'   => 'Drupal\quizz_migrate\Branch4x\RelationshipMigration',
          'group_name'   => 'quiz4x',
          'dependencies' => array('quiz_revision', 'quiz_question_type'),
      ),
  );

  $api['migrations'] += array(
      'quiz_result' => array(
          'class_name'   => 'Drupal\quizz_migrate\Branch4x\ResultMigration',
          'group_name'   => 'quiz4x',
          'dependencies' => array('quiz_relationship'),
      ),
  );

  return $api;
}

/**
 * Implements hook_enable().
 */
function quizz_migrate_enable() {
  Migration::registerMigration('Drupal\quizz_migrate\Branch4x\QuizMigration', 'quiz', array('group_name' => 'quiz4x'));
  Migration::registerMigration('Drupal\quizz_migrate\Branch4x\QuizRevisionMigration', 'quiz_revision', array('group_name' => 'quiz4x'));
  Migration::registerMigration('Drupal\quizz_migrate\Branch4x\QuestionTypeMigration', 'quiz_question_type', array('group_name' => 'quiz4x'));
  Migration::registerMigration('Drupal\quizz_migrate\Branch4x\RelationshipMigration', 'quiz_relationship', array('group_name' => 'quiz4x'));
  Migration::registerMigration('Drupal\quizz_migrate\Branch4x\ResultMigration', 'quiz_result', array('group_name' => 'quiz4x'));
  Migration::registerMigration('Drupal\quizz_migrate\Branch4x\AnswerMigration', 'quiz_answer', array('group_name' => 'quiz4x'));
  Migration::deregisterMigration('quiz_question');
}

function quizz_migrate_enable_question_type($node_type) {
  if (quizz_question_get_handler_info($node_type)) {
    Migration::registerMigration(
      'Drupal\quizz_migrate\Branch4x\QuestionMigration', "quiz_question__{$node_type}", array('bundle' => $node_type, 'group_name' => 'quiz4x_question')
    );

    Migration::registerMigration(
      'Drupal\quizz_migrate\Branch4x\QuestionRevisionMigration', "quiz_question_revision__{$node_type}", array('bundle' => $node_type, 'group_name' => 'quiz4x_question_revision')
    );
  }
}

/**
 * Implements hook_modules_enabled()
 */
function quizz_migrate_modules_enabled($modules) {
  foreach ($modules as $module) {
    if (function_exists("{$module}_quizz_question_info")) {
      quizz_migrate_module_enabled($module);
    }
  }
}

function quizz_migrate_module_enabled($module) {
  $handlers = module_invoke($module, 'quizz_question_info');
  foreach (array_keys($handlers) as $name) {
    if (db_query('SELECT 1 FROM {node_type} WHERE type = :type', array(':type' => $name))->fetchColumn()) {
      quizz_migrate_enable_question_type($name);
    }
  }
}
